# Generated by Django 2.2.1 on 2019-06-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190613_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'UserMessageContent', 'verbose_name_plural': 'UserMessageContent'},
        ),
    ]
